fit:
# procs: None
  populations: 10
  population_size: 40
  ncycles_per_iteration: 500
  niterations: 1000
  timeout_in_seconds: 3600 # 1 hour
  maxsize: 25
  binary_operators: ['*', '+', '-', '/']
  unary_operators: ['sin', 'cos', 'exp', 'log']
  nested_constraints:
    sin:
      sin: 0
      cos: 0
    cos:
      sin: 0
      cos: 0
    exp:
      exp: 0
    log:
      log: 0
  progress: True
  weight_randomize: 0.1
  precision: 32
  warm_start: False
  turbo: True
  update: False
  verbosity: 0
